#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Mike Wilson
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Usage: [how to run the script, e.g., ./script_name.sh <arguments>]
# Author: Mike Wilson <mike@mikewilsonstl.com>
# Created: 2025-12-15T16:22:03-05:00
# Description: [brief purpose of the script]

set -euo pipefail
shopt -s extglob

main() {
    systemd-cgls --no-pager
}

main "$@"
