#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Mike Wilson
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Usage: ./cgmon
# Author: Mike Wilson <mike@mikewilsonstl.com>
# Created: 2025-12-15T16:22:03-05:00
# Description: Checks all active cg processes.

set -euo pipefail
shopt -s extglob

main() {
    systemd-cgls --no-pager
}

main "$@"
